fix(fuentbit): update PSP resource with missing values
kube-logging/logging-operator pull request #1142
Opened 2022-11-30 10:27 UTC by aslafy-z

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes https://github.com/banzaicloud/logging-operator/issues/731
| License         | Apache 2.0

### What's in this PR?

Update the Fluentbit PSP with missing hostpaths, hostports and hostnetwork.

### Why?

Logging operator cannot be deployed on GKE with the current default.

### Checklist

- [x] Code meets the [Developer Guide](https://github.com/banzaicloud/developer-guide)

2023-01-18 10:24 UTC, siliconbrain requested changes

2023-01-18 10:24 UTC, siliconbrain commented on pkg/resources/fluentbit/psp.go
> +			if r.Logging.Spec.FluentbitSpec.Metrics != nil && r.Logging.Spec.FluentbitSpec.BufferVolumeMetrics.Port != 0 {
```suggestion
			if r.Logging.Spec.FluentbitSpec.BufferVolumeMetrics != nil && r.Logging.Spec.FluentbitSpec.BufferVolumeMetrics.Port != 0 {
```

2023-01-18 10:25 UTC, siliconbrain requested changes

2023-01-18 10:25 UTC, siliconbrain commented on pkg/resources/fluentbit/psp.go
> +		if r.Logging.Spec.FluentbitSpec.BufferStorageVolume.HostPath != nil {
```suggestion
		if r.Logging.Spec.FluentbitSpec.BufferStorageVolume != nil && r.Logging.Spec.FluentbitSpec.BufferStorageVolume.HostPath != nil {
```

2023-01-18 11:55 UTC, siliconbrain approved these changes

2023-01-18 12:07 UTC, aslafy-z commented on pkg/resources/fluentbit/psp.go
> +		if r.Logging.Spec.FluentbitSpec.BufferStorageVolume != nil && r.Logging.Spec.FluentbitSpec.BufferStorageVolume.HostPath != nil {
I guess I also misread the type, I checked your proposals I guess wrongly :)

2023-02-22 16:24 UTC, siliconbrain approved these changes

2023-03-08 21:43 UTC, ahma approved these changes
LGTM Thanks

2023-03-08 21:43 UTC, merged