fix: ssl version in opensearch
kube-logging/logging-operator pull request #1330
Opened 2023-05-12 19:11 UTC by joseacl

Fixes https://github.com/kube-logging/logging-operator/issues/1088
It's still pending changes in the CRD for the helm chart https://github.com/kube-logging/helm-charts/
I'll do it shortly.

2023-05-16 14:27 UTC, pepov commented
@joseacl it says:
> Commit sha: [bf04ff2](https://github.com/kube-logging/logging-operator/pull/1330/commits/bf04ff2d8a9b4dd99e9f194b45f07fcd5f1686b1), Author: Jose Antonio Cortes Lopez, Committer: José Antonio Cortés López; Expected "Jose Antonio Cortes Lopez [jacortes@theworkshop.com](mailto:jacortes@theworkshop.com)", but got "joseacl [joseacl@gmail.com](mailto:joseacl@gmail.com)".

2023-05-16 16:13 UTC, joseacl commented
> @joseacl it says:
> 
> > Commit sha: [bf04ff2](https://github.com/kube-logging/logging-operator/pull/1330/commits/bf04ff2d8a9b4dd99e9f194b45f07fcd5f1686b1), Author: Jose Antonio Cortes Lopez, Committer: José Antonio Cortés López; Expected "Jose Antonio Cortes Lopez [jacortes@theworkshop.com](mailto:jacortes@theworkshop.com)", but got "joseacl [joseacl@gmail.com](mailto:joseacl@gmail.com)".

You're right, sorry it was my fault. Already fixed, thanks!

2023-05-17 07:38 UTC, pepov requested changes
would you please bump the logging operator chart's minor version?

2023-05-17 07:38 UTC, pepov commented on pkg/sdk/logging/model/output/opensearch_test.go
> +  ssl_version TLSv1_2
nit: not a new thing, but would you please replace tabs with spaces (or vice versa) so that the indentation stays consistent?

2023-05-17 12:04 UTC, joseacl commented
> would you please bump the logging operator chart's minor version?

Also done https://github.com/kube-logging/helm-charts/pull/22/commits/c206fc3c9f73326af1df8ebcc1370e5228f3fba8

2023-05-18 04:26 UTC, pepov commented
this a temporary ugliness, but the chart should be in sync with kube-logging/helm-charts so please bump the chart version here as well

2023-05-18 12:25 UTC, pepov approved these changes

2023-05-18 13:31 UTC, merged