Add mongodb output to syslog-ng #1450
kube-logging/logging-operator pull request #1455
Opened 2023-09-04 10:18 UTC by OverOrion

Continuation of https://github.com/kube-logging/logging-operator/pull/1255.

My question is about the `write-concern` option, which can take a builtin keyword or a non-negative integer (the [docs](https://axoflow.com/docs/axosyslog-core/chapter-destinations/configuring-destinations-mongodb/reference-destination-mongodb/#mongodb-option-write-concern) does not say the latter for some reason, might need to be looked into). In the last commit I refactored it to use an interface, however the ergonomics are still not great, is there any way to somehow improve it, just leave as is or even revert back to the `RawString` version?

2023-09-05 08:21 UTC, pepov commented
I don't see too much value added through the WriteConcern interface to be honest, so I would opt for the basic rawstring solution.

2023-09-05 12:19 UTC, kristofgyuracz requested changes

2023-09-05 12:19 UTC, kristofgyuracz commented on pkg/sdk/logging/model/syslogng/output/mongodb.go
> +	//
Please document the field.

2023-09-07 07:07 UTC, pepov approved these changes

2023-09-07 07:07 UTC, kristofgyuracz approved these changes
LGTM, thanks.

2023-09-08 07:09 UTC, merged