Extract fluentd crd
kube-logging/logging-operator pull request #1584
Opened 2023-11-20 09:16 UTC by OverOrion

TODO: 
- [ ] fill description
- [ ] add examples

Fixes #1574.

2023-11-21 14:46 UTC, kristofgyuracz requested changes

2023-11-21 14:47 UTC, kristofgyuracz commented
Otherwise it looks good, great work!

2023-11-22 08:28 UTC, OverOrion commented on pkg/resources/model/repository.go
> +	// TODO add a bit more verbose error handling
Nope, not anymore, thanks!

2023-11-22 08:29 UTC, OverOrion commented on pkg/resources/model/repository.go
> +	// logging_resource.status :=
Nice catch, cleaned it up in the latest iteration!

2023-11-22 08:30 UTC, kristofgyuracz approved these changes

2023-11-22 09:36 UTC, aslafy-z commented
We have FluentbitAgent, don't we want to name Fluentd like FluentdAggregator or something?

2023-11-22 13:37 UTC, pepov commented
Be aware of this: https://github.com/kube-logging/logging-operator/pull/1592

2023-11-29 12:50 UTC, pepov commented on pkg/resources/fluentd/fluentd.go
> +	// No fluentdSpec yet, explicitly ask for a requeue to short circuit the controller loop after the status update
this is unnecessary as fluentdSpec will always exist at this point, also we leverage the watch instead of having to requeue

2023-12-05 09:14 UTC, pepov commented
Regarding naming one last time. After considering a few other options as well, we would like to go with `FluentdConfig` for simplicity. 

This will leave us with:
`FluentbitAgent`
`FluentdConfig`
`SyslogNGConfig`

And eventually (planned):
`SyslogNGAgent`

The idea is to keep the names short and use the "agent" classifier for the agents only.

2023-12-06 17:13 UTC, tarokkk approved these changes
LGTM Thanks!

2023-12-06 17:17 UTC, merged

2024-04-23 07:42 UTC, frit0-rb commented
I got a question about this change, all config about Fluentd inside of Logging it will be in FluentdConfig CRD?? For example the PVC or security? In the info about 4.5.1 the info is still in logging CRD [https://kube-logging.dev/4.5/docs/logging-infrastructure/fluentd/#custom-pvc-volume-for-fluentd-buffers](url)

2024-04-29 11:01 UTC, pepov commented
They are available in both. We don't plan to remove the fluentd config from the logging resource in versions 4.x as it would break existing clients. We are thinking in a deprecation policy that would phase out the fluentd config from the logging resource through a number of minor version upgrades.