This pull request is related with #1616
kube-logging/logging-operator pull request #1617
Opened 2023-12-12 09:46 UTC by bbyreddy

Ensured that the custom PVC source details specified in the fluentd.extraVolumes.volume.pvc.source.claimName of the fluentd definition are honoured instead of always attempting to create a new PVC.

Introduced empty checks to the PersistentVolumeClaim.PersistentVolumeClaimSpec and PersistentVolumeClaim.PersistentVolumeSource structures and ApplyPVCForStatefulSet() and ApplyVolumeForPodSpec() functions are invoked only when the respective structures are not empty.

2024-01-11 12:06 UTC, aslafy-z commented on pkg/resources/fluentd/statefulset.go
> +	return string(searilizedPvcSpec) == `{"resources":{}}`
```suggestion
	serilizedPvcSpec, _ := json.Marshal(pvcSpec) // Json serialization should not fail, hence the error is ignored
	return string(serilizedPvcSpec) == `{"resources":{}}`
```

2024-01-11 12:06 UTC, aslafy-z commented on pkg/resources/fluentd/statefulset.go
> +	return string(searilizedPvcSource) == `{}`
```suggestion
	serilizedPvcSource, _ := json.Marshal(pvcSource) // Json serialization should not fail, hence the error is ignored
	return string(serilizedPvcSource) == `{}`
```

2024-01-11 12:07 UTC, aslafy-z requested changes
I spot a couple of typos, can you please fix them?

2024-01-11 14:33 UTC, pepov commented
I promised to look into how we could make the comparison more efficient, sorry I haven't been able to get back to that

2024-01-12 13:49 UTC, bbyreddy commented
> I promised to look into how we could make the comparison more efficient, sorry I haven't been able to get back to that

Hi @pepov and @aslafy-z ,
There is another PR https://github.com/kube-logging/logging-operator/pull/1622 created by @OverOrion , which resolves this issue. I'm not sure which direction you want to take to resolve this issue.
Thanks!

2024-01-12 14:37 UTC, bbyreddy commented on pkg/resources/fluentd/statefulset.go
> +	return string(searilizedPvcSource) == `{}`
Corrected the spelling.

2024-01-12 15:16 UTC, pepov commented
@bbyreddy we want to keep this instead of introducing yet another huge field to the fluentd spec

2024-01-12 15:20 UTC, pepov commented
I'm planning to add some technical docs as well

2024-01-15 18:13 UTC, bbyreddy commented
> @bbyreddy can you check if the solution that works for you?

@pepov , yes, this works perfectly fine and is much simpler as well. 
Please let me know if I need to do anything to get this PR merged into the master.
Thanks!

2024-01-15 18:53 UTC, pepov approved these changes

2024-01-16 08:44 UTC, bbyreddy commented
> I spotted a couple of typos, can you please fix them? Also, can you please update the PR name so it reflects the changes and add `fixes #1616` in the PR description? You will also have to sign your commits, see https://github.com/kube-logging/logging-operator/pull/1617/checks?check_run_id=20378816523.

@aslafy-z , you may have to mark this as resolved and approve the PR as the code has changed now and doesn't have the typos anymore. Thanks!

2024-01-16 12:13 UTC, OverOrion approved these changes

2024-01-16 12:28 UTC, pepov commented
@aslafy-z typos has been fixed and signoff done, I'm merging this

2024-01-16 12:28 UTC, merged