Feat: add json format for fluentd output
kube-logging/logging-operator pull request #1657
Opened 2024-01-30 18:19 UTC by pbdger

This change adds a feature to set FluentD output to json format.

```
spec:
  fluentd:
    logFormat: json
```

The default is still text. Adding the new value logFormat: json will modify the fluendtd-Container file /fluentd/etc/input.conf.

2024-01-30 19:25 UTC, pepov requested changes

2024-01-30 19:25 UTC, pepov commented on pkg/sdk/logging/api/v1beta1/fluentd_types.go
> +			f.LogLevel = "text"
```suggestion
			f.LogFormat = "text"
```

2024-01-30 19:53 UTC, pepov commented
@pbdger please signoff your commits: https://github.com/kube-logging/logging-operator/pull/1657/checks?check_run_id=21033484471

2024-02-26 15:49 UTC, pepov commented
@pbdger do you plan to fix the CI issues? (You should run a `make check-diff` locally and push the changes, as well as add signoff to all your commits.)

2024-04-29 13:18 UTC, pepov commented
@pbdger updated the PR and squashed commits into one to pass the checks

2024-04-29 13:20 UTC, pepov approved these changes

2024-04-29 15:46 UTC, aslafy-z approved these changes

2024-04-29 16:39 UTC, merged